import os
from skbuild import setup, constants
from setuptools import find_packages

scripts = [
    "vmtk",
    "vmtkactivetubes",
    "vmtkbifurcationprofiles",
    "vmtkbifurcationreferencesystems",
    "vmtkbifurcationsections",
    "vmtkbifurcationvectors",
    "vmtkboundarylayer",
    "vmtkboundarylayer2",
    "vmtkboundaryreferencesystems",
    "vmtkbranchclipper",
    "vmtkbranchextractor",
    "vmtkbranchgeometry",
    "vmtkbranchmapping",
    "vmtkbranchmetrics",
    "vmtkbranchpatching",
    "vmtkbranchsections",
    "vmtkcenterlineattributes",
    "vmtkcenterlinegeometry",
    "vmtkcenterlineinterpolation",
    "vmtkcenterlinelabeler",
    "vmtkcenterlinemerge",
    "vmtkcenterlinemeshsections",
    "vmtkcenterlinemodeller",
    "vmtkcenterlineoffsetattributes",
    "vmtkcenterlineresampling",
    "vmtkcenterlines",
    "vmtkcenterlinesections",
    "vmtkcenterlinesmoothing",
    "vmtkcenterlinestonumpy",
    "vmtkcenterlineviewer",
    "vmtkdelaunayvoronoi",
    "vmtkdijkstradistancetopoints",
    "vmtkdistancetocenterlines",
    "vmtkdistancetospheres",
    "vmtkendpointextractor",
    "vmtkentityrenumber",
    "vmtkflowextensions",
    "vmtkgeodesicsurfaceresolution",
    "vmtkicpregistration",
    "vmtkimagebinarize",
    "vmtkimagecast",
    "vmtkimagecompare",
    "vmtkimagecompose",
    "vmtkimagecurvedmpr",
    "vmtkimagefeaturecorrection",
    "vmtkimagefeatures",
    "vmtkimageinitialization",
    "vmtkimagemipviewer",
    "vmtkimagemorphology",
    "vmtkimagenormalize",
    "vmtkimageobjectenhancement",
    "vmtkimageotsuthresholds",
    "vmtkimagereader",
    "vmtkimagereslice",
    "vmtkimageseeder",
    "vmtkimageshiftscale",
    "vmtkimagesmoothing",
    "vmtkimagetonumpy",
    "vmtkimagevesselenhancement",
    "vmtkimageviewer",
    "vmtkimagevoipainter",
    "vmtkimagevoiselector",
    "vmtkimagewriter",
    "vmtklevelsetsegmentation",
    "vmtklineartoquadratic",
    "vmtklineresampling",
    "vmtklocalgeometry",
    "vmtkmarchingcubes",
    "vmtkmeshaddexternallayer",
    "vmtkmesharrayoperation",
    "vmtkmeshboundaryinspector",
    "vmtkmeshbranchclipper",
    "vmtkmeshclipcenterlines",
    "vmtkmeshclipper",
    "vmtkmeshcompare",
    "vmtkmeshconnectivity",
    "vmtkmeshcutter",
    "vmtkmeshdatareader",
    "vmtkmeshextractpointdata",
    "vmtkmeshgenerator", "vmtkmeshlambda2",
    "vmtkmeshlinearize", "vmtkmeshmerge",
    "vmtkmeshmergetimesteps",
    "vmtkmeshpolyballevaluation",
    "vmtkmeshprojection",
    "vmtkmeshreader",
    "vmtkmeshscaling",
    "vmtkmeshtetrahedralize",
    "vmtkmeshtetrahedralize2",
    "vmtkmeshtonumpy", "vmtkmeshtosurface",
    "vmtkmeshtransform", "vmtkmeshtransformtoras",
    "vmtkmeshvectorfromcomponents", "vmtkmeshviewer",
    "vmtkmeshviewer2", "vmtkmeshvolume",
    "vmtkmeshvorticityhelicity", "vmtkmeshwallshearrate",
    "vmtkmeshwriter", "vmtkmeshwriter2", "vmtknetworkeditor",
    "vmtknetworkextraction", "vmtknetworkwriter", "vmtknumpyreader",
    "vmtknumpytocenterlines", "vmtknumpytoimage", "vmtknumpytomesh",
    "vmtknumpytosurface", "vmtknumpywriter", "vmtkparticletracer",
    "vmtkpathlineanimator", "vmtkpointsplitextractor", "vmtkpointtransform",
    "vmtkpolyballmodeller", "vmtkpotentialfit", "vmtkpythonscript", "vmtkrbfinterpolation",
    "vmtkrenderer", "vmtkrendertoimage", "vmtksurfaceappend", "vmtksurfacearrayoperation",
    "vmtksurfacearraysmoothing", "vmtksurfacebooleanoperation", "vmtksurfacecapper",
    "vmtksurfacecelldatatopointdata", "vmtksurfacecenterlineprojection",
    "vmtksurfacecliploop", "vmtksurfaceclipper", "vmtksurfacecompare",
    "vmtksurfaceconnectivity", "vmtksurfacecurvature", "vmtksurfacedecimation",
    "vmtksurfacedistance", "vmtksurfaceendclipper", "vmtksurfaceextractannularwalls",
    "vmtksurfaceextractinnercylinder", "vmtksurfacekiteremoval", "vmtksurfaceloopextraction",
    "vmtksurfacemassproperties", "vmtksurfacemodeller", "vmtksurfacenormals",
    "vmtksurfacepointdatatocelldata", "vmtksurfacepolyballevaluation",
    "vmtksurfaceprojection", "vmtksurfacereader",
    "vmtksurfacereferencesystemtransform", "vmtksurfaceregiondrawing",
    "vmtksurfaceremeshing", "vmtksurfaceresolution", "vmtksurfacescaling",
    "vmtksurfacesmoothing", "vmtksurfacesubdivision", "vmtksurfacetomesh",
    "vmtksurfacetonumpy", "vmtksurfacetransform", "vmtksurfacetransforminteractive",
    "vmtksurfacetransformtoras", "vmtksurfacetriangle", "vmtksurfaceviewer",
    "vmtksurfacewriter", "vmtksurfacewriter2", "vmtksurfmesh", "vmtktetgen",
    "vmtktetringenerator", "vmtkthreshold",
    "pypebatch", "pypepad", "pyperun", "pypeserver", "pypetest", "pypetestrunner", "pypewrapper"
]

scripts_paths = [os.path.join("./", constants.CMAKE_INSTALL_DIR(), "bin", s) for s in scripts]
setup(
    name='vmtk-infervision',
    version='1.4.0',
    author='vmtk author',
    packages=["vmtk"],
    scripts=scripts_paths,
    package_dir={"vmtk": "vmtk"},
    description="vmtk",
    classifiers=[
        "Programming Language :: Python",
        "Programming Language :: C++",
    ]
)
